from multi_task_rec.dataset import get_movielens_dataset
from multi_task_rec.evaluation import mrr_score, mse_score
from multi_task_rec.models import MultiTaskNet
from multi_task_rec.multitask import MultitaskModel